### ISSUE TITLE
2.Basics#명령 종료 문자 첫번째 예시가 좀 헷갈립니다.

### ISSUE THREAD

**Issue by oiojin831** [mug896/bash-shell#4]
일단 좋은 책 써주셔서 감사합니다.

> 특히 주의할 점은 명령 grouping 을위해 중괄호 { } 사용시는 명령의 인수와 구분을 위해 마지막에 ; 를 붙여줘야 합니다.
> \# 명령들을 한줄에 연이어 쓸 경우는 ';' 를 사용해야 한다.

이부분에 해당하는 첫번째 예시에서
```
$ for i in {1..3} do echo $i done
$ for i in {1..3}; do echo $i; done
```
{1..3}뒤에오는 ';'가 명령 grouping의 { }때문에 쓰는 ';'인지 명려의 인수와 구분을 위한건지 헷갈리네요.
제가 for loop의 do 와 done이
```
$ for i in {1...3}  #줄바꿈
do echo $i  #줄바꿈
done
> 빈줄 출력?

$ for i in {1...3};  #줄바꿈
do echo $i;  #줄바꿈
done
> 정상작동

$ for i in {1...3}; do  #줄바꿈
echo $i  #줄바꿈
done
> 정상작동
for i in {1..3}; do; echo $i; done
> 정상작동
```
{1..3}을 위한 ';'인게 맞는건가요?

**Comment by mug896** [comment]
> for i in {1..3} do echo $i; done

문장에서 사용된 {1..3} 는 명령 그룹이 아니고 brace 확장 기능으로 뒷부분에 나옵니다.
이것은 한줄에 명령을 연이어 쓸경우에 대한 예제로 do 키워드 앞에 `;` 를 붙이지 않아 오류가 발생합니다.

>$ for i in {1..3} do echo $i; done
>bash: syntax error near unexpected token 'done'

다음과 같이 do 키워드 앞에 `;` 를 붙여야 정상적으로 실행됩니다.

>for i in {1..3}; do echo $i; done
1
2
3
