### ISSUE TITLE
PDF로 출력해서 볼 수 있는 방법이 있나요?

### ISSUE THREAD

**Issue by ghost** [mug896/bash-shell#6]
죄송하지만 Gitbook 웹페이지에 PDF로 볼 수 있는 메뉴가 없어서 혹시 PDF로 볼 수 있는 메뉴 추가 가능하신지 여쭙습니다 ^^

**Comment by mug896** [comment]
gitbook 사이트가 이전에 속도가 많이 느려서 github 으로 옮겼습니다.
github 에는 pdf 출력이 없는걸로 알고 있습니다.

**Comment by ghost** [comment]
@mug896 답변 감사합니다!
