### ISSUE TITLE
PDF로 한번에 다운 받을 방법을 알려주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by ghost** [mug896/bash-shell#7]
안녕하세요. 좋은 자료 만들어 주셔서 감사합니다.

다만, PDF로 한번에 받을 수 있는 방법은 없는지요 ?

알려주시면 감사하겠습니다.

**Comment by mug896** [comment]
예전에 올렸던 gitbook 에서는 PDF 다운 기능이 있었는데 github 에는 PDF 다운 기능이 따로 없습니다.
github 에서 download 버튼을 이용해 받으시면 html 화일이기 때문에 브라우저로 간단히 보실수 있습니다.

**Comment by mug896** [comment]
> 안녕하세요. 좋은 자료 만들어 주셔서 감사합니다.
> 
> 다만, PDF로 한번에 받을 수 있는 방법은 없는지요 ?
> 
> 알려주시면 감사하겠습니다.
